trigger:
- master

pool:
  name: 'myUbuntuAgentPool'

jobs:
- job: Build_PushToDockerHub
  displayName: 'Build, Push to Docker Hub'
  steps:
  - checkout: self

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
    displayName: 'Build Java Application'
  

 # Docker - Login to Docker Hub using Service Connection
  - task: Docker@2
    displayName: 'Docker Login to Docker Hub'
    inputs:
      command: 'login'
      containerRegistry: 'dockerHub' 
 
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub'
      repository: 'oumymajellali/backend'
      command: 'buildAndPush'
      Dockerfile: 'dockerfile'
   
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerHub'
      repository: 'oumymajellali/frontend'
      command: 'buildAndPush'
      Dockerfile: 'frontend/dockerfile' 