trigger:
- master

pool:
  name: 'myUbuntuAgentPool'

jobs:
- job: Build_PushToDockerHub
  displayName: 'Build, Push to Docker Hub'
  steps:
  - checkout: self

  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      publishJUnitResults: true
    displayName: 'Build Java Application'

  - task: Docker@2
    displayName: 'Docker Login to Docker Hub'
    inputs:
      command: 'login'
      containerRegistry: 'Docker' 

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'oumymajellali/backend'
      command: 'buildAndPush'
      Dockerfile: 'dockerfile'

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker'
      repository: 'oumymajellali/frontend'
      command: 'buildAndPush'
      Dockerfile: 'frontend/dockerfile'
